# argocd-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-web-img
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-web-img
    spec:
      containers:
      - name: argocd-img-container
        image: gksehddus202/app-with-argocd-img:f73227b716dd8c48f5d26b158815b347926d5165
